name: adventofcode2021

dependencies:
  - base >= 4.7 && < 5
  - adventofcode-common
  - containers
  - megaparsec
  - parser-combinators
  - PSQueue
  - split
  - text

default-extensions:
  - OverloadedStrings
  - TupleSections

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  adventofcode2021-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode2021
      - hspec
      - hspec-discover
