name: adventofcode-common

dependencies:
  - base >= 4.7 && < 5
  - advent-of-code-api
  - containers
  - PSQueue
  - text

default-extensions:
  - OverloadedStrings
  - TupleSections

library:
  source-dirs: src
  ghc-options:
    - -Wall
