resolver: lts-21.25

packages:
  - adventofcode-common
  - adventofcode2015
  - adventofcode2017
  - adventofcode2020
  - adventofcode2021
  - adventofcode2023
  - adventofcode2024

extra-deps:
  - PSQueue-1.1.1
  - parser-combinators-1.3.0
  - memoize-1.1.2
