name: adventofcode2020

dependencies:
  - base >= 4.7 && < 5
  - adventofcode-common
  - containers
  - megaparsec
  - parser-combinators
  - regex-pcre-builtin
  - text
  - vector

default-extensions:
  # - OverloadedStrings # this doesn't play too well with regex-pcre-builtin
  - TupleSections

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  adventofcode2020-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode2020
      - hspec
      - hspec-discover
