name: adventofcode2015

dependencies:
  - base >= 4.7 && < 5
  - adventofcode-common
  - array
  - containers
  - json
  - megaparsec
  - MissingH
  - regex-pcre-builtin
  - text

default-extensions:
  # - OverloadedStrings # this doesn't play too nice with regex-pcre-builtin
  - TupleSections

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  adventofcode2015-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - adventofcode2015
      - hspec
      - hspec-discover
